arch: amd64
os: linux
language: generic
dist: focal
addons:
     apt:
     - gcc-aarch64-linux-gnu
script:
- git config --global user.name "홍길동"
- git config --global user.email "support@webisfree.com" 
- yes | git clone https://github.com/roynatech2544/Samsung_Device_A20e_Kernel.git -b Kernel_4.4.177
- cd Samsung_Device_A20e_Kernel
- export ANDROID_MAJOR_VERSION=q
- export ARCH=arm64
- make exynos7885-a20ektt_defconfig
- make -j64
- mkdir out
- cp arch/arm64/boot/Image out 
- cp arch/arm64/boot/dts/exynos/dtbo/exynos7884B-a20e_kor_ktt_00.dtbo out
- cp arch/arm64/boot/dts/exynos/dtbo/exynos7884B-a20e_kor_ktt_00.dts out
- zip -r Kernel out
- curl --upload-file Kernel.zip https://transfer.sh/Kernel.zip
